# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [10]:
s1 = pd.Series(np.random.randint(1,5,size=100, dtype='l'))
s2 = pd.Series(np.random.randint(1,4,size=100, dtype='l'))
s3 = pd.Series(np.random.randint(10000,30000,size=100, dtype='l'))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [18]:
df = pd.concat([s1, s2, s3], axis=1, ignore_index=True)

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [19]:
# df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']
df.rename(columns={0:'bedrs',1:'bathrs', 2:'price_sqr_meter'}, inplace = True)
df

    bedrs  bathrs  price_sqr_meter
0       2       3            20846
1       2       3            20412
2       3       1            28543
3       3       3            12910
4       1       3            16225
..    ...     ...              ...
95      4       3            22330
96      1       2            20523
97      4       2            18786
98      4       2            18704
99      3       3            22405

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [21]:
bigcolumn = pd.concat([s1, s2, s3]) # ignore_index=True)
bigcolumn = pd.DataFrame(bigcolumn)
bigcolumn

        0
0       2
1       2
2       3
3       3
4       1
..    ...
95  22330
96  20523
97  18786
98  18704
99  22405

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [22]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [25]:
bigcolumn.reset_index(drop=True, inplace = True)
bigcolumn

         0
0        2
1        2
2        3
3        3
4        1
..     ...
295  22330
296  20523
297  18786
298  18704
299  22405

[300 rows x 1 columns]