# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [27]:
import pandas as pd
import numpy as np
import inspect

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [6]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep = '\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Assign it to a variable called chipo.

### Step 4. See the first 10 entries

In [7]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 5. What is the number of observations in the dataset?

In [10]:
# Solution 1

df.shape[0]

4622

In [11]:
# Solution 2

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 6. What is the number of columns in the dataset?

In [13]:
df.shape[1]

5

### Step 7. Print the name of all the columns.

In [16]:
for i in df.columns.to_list():
    print(i)

order_id
quantity
item_name
choice_description
item_price

### Step 8. How is the dataset indexed?

In [20]:
df.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [73]:
#groupby item_name, show only quantity column, apply sum
df.groupby('item_name')[['quantity']].sum().sort_values(['quantity'], ascending=False).head(3)

                     quantity
item_name
Chicken Bowl              761
Chicken Burrito           591
Chips and Guacamole       506

In [74]:
#groupby item_name, aggregate on order_id and quantity
df.groupby('item_name').agg(total_orders=('order_id','count'), total_quantity=('quantity', 'sum')).sort_values('total_quantity', ascending = False).head(3)

                     total_orders  total_quantity
item_name
Chicken Bowl                  726             761
Chicken Burrito               553             591
Chips and Guacamole           479             506

In [48]:
# check what kind of parameters a function has
print(inspect.getfullargspec(df.groupby))

FullArgSpec(args=['self', 'by', 'axis', 'level', 'as_index', 'sort', 'group_keys', 'observed', 'dropna'], varargs=None, varkw=None, defaults=(None, <no_default>, None, True, True, True, <no_default>, True), kwonlyargs=[], kwonlydefaults=None, annotations={'return': 'DataFrameGroupBy', 'axis': 'Axis | lib.NoDefault', 'level': 'IndexLabel | None', 'as_index': 'bool', 'sort': 'bool', 'group_keys': 'bool', 'observed': 'bool | lib.NoDefault', 'dropna': 'bool'})

### Step 10. For the most-ordered item, how many items were ordered?

In [85]:
df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1).iloc[0]

761

### Step 11. What was the most ordered item in the choice_description column?

In [102]:
df['choice_description'].iloc[4]

'[Tomatillo-Red Chili Salsa (Hot), [Black Beans, Rice, Cheese, Sour Cream]]'

In [109]:
df.groupby('choice_description').agg(item_count=('item_name','count'), total_quantity=('quantity', 'sum')).sort_values('total_quantity', ascending=False).head(3)

                    item_count  total_quantity
choice_description
[Diet Coke]                134             159
[Coke]                     123             143
[Sprite]                    77              89

### Step 12. How many items were orderd in total?

In [111]:
df.quantity.sum()

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [114]:
df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

#### Step 13.b. Create a lambda function and change the type of item price

In [136]:
df['item_price'] = df[['item_price']].applymap(lambda x: float(x.replace('$', '').strip()))
#

C:\Users\I38724\AppData\Local\Temp\ipykernel_11024\3257699393.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df['item_price'] = df[['item_price']].applymap(lambda x: float(x.replace('$', '').strip()))

#### Step 13.c. Check the item price type

In [138]:
df.item_price.dtypes

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [143]:
print(f'revenue: ${(df.item_price*df.quantity).sum()}')

revenue: $39237.02

### Step 15. How many orders were made in the period?

In [145]:
df.order_id.nunique()

1834

In [155]:
df.order_id.value_counts().sort_index().count()

1834

### Step 16. What is the average revenue amount per order?

In [156]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [163]:
df['total_price'] = df.quantity*df.item_price

In [169]:
df.drop('total_price', axis=1, inplace=True)

In [170]:
# Solution 1
df['revenue'] = df.quantity*df.item_price
df.groupby('order_id')['revenue'].sum().mean()

21.39423118865867

In [4]:
# Solution 2

### Step 17. How many different items are sold?

In [171]:
df.item_name.nunique()

50